from classes.ENUMS.block_codes import ExtendedEnum

"""Biome ID enums, a list of minecraft biome ids, returned by minecraft program"""


class biome_ids(ExtendedEnum):
    OCEAN = 0
    PLAINS = 1
    DESERT = 2
    WINDSWEPT_HILLS = 3
    FOREST = 4
    TAIGA = 5
    SWAMPLAND = 6
    RIVER = 7
    HELL = 8
    THE_END = 9
    FROZEN_OCEAN = 10
    FROZEN_RIVER = 11
    ICE_PLAINS = 12
    ICE_MOUNTAINS = 13
    MUSHROOM_ISLAND = 14
    MUSHROOM_ISLAND_SHORE = 15
    BEACH = 16
    DESERT_HILLS = 17
    FOREST_HILLS = 18
    TAIGA_HILLS = 19
    EXTREME_HILLS_EDGE = 20
    JUNGLE = 21
    JUNGLE_HILLS = 22
    JUNGLE_EDGE = 23
    DEEP_OCEAN = 24
    STONE_BEACH = 25
    COLD_BEACH = 26
    BIRCH_FOREST = 27
    BIRCH_FOREST_HILLS = 28
    ROOFED_FOREST = 29
    COLD_TAIGA = 30
    COLD_TAIGA_HILLS = 31
    MEGA_TAIGA = 32
    MEGA_TAIGA_HILLS = 33
    WINDSWEPT_FOREST = 34
    SAVANNA = 35
    SAVANNA_PLATEAU = 36
    MESA = 37
    MESA_PLATEAU = 38
    MESA_PLATEAU_STONE = 39
    WARM_OCEAN = 40
    LUKEWARM_OCEAN = 41
    COLD_OCEAN = 42
    DEEP_WARM_OCEAN = 43
    DEEP_LUKEWARM_OCEAN = 44
    DEEP_COLD_OCEAN = 45
    DEEP_FROZEN_OCEAN = 46
    LEGACY_FROZEN_OCEAN = 47
    SUNFLOWER_PLAINS = 129
    DESERT_MUTATED = 130
    WINDSWEPT_GRAVELLY_HILLS = 131
    FLOWER_FOREST = 132
    TAIGA_MUTATED = 133
    SWAMPLAND_MUTATED = 134
    ICE_PLAINS_SPIKES = 140
    JUNGLE_MUTATED = 149
    JUNGLE_EDGE_MUTATED = 151
    BIRCH_FOREST_MUTATED = 155
    BIRCH_FOREST_HILLS_MUTATED = 156
    ROOFED_FOREST_MUTATED = 157
    COLD_TAIGA_MUTATED = 158
    REDWOOD_TAIGA_MUTATED = 160
    REDWOOD_TAIGA_HILLS_MUTATED = 161
    EXTREME_HILLS_PLUS_TREES_MUTATED = 162
    SAVANNA_MUTATED = 163
    SAVANNA_PLATEAU_MUTATED = 164
    MESA_BRYCE = 165
    MESA_PLATEAU_MUTATED = 166
    MESA_PLATEAU_STONE_MUTATED = 167
    BAMBOO_JUNGLE = 168
    BAMBOO_JUNGLE_HILLS = 169
    SOULSAND_VALLEY = 178
    CRIMSON_FOREST = 179
    WARPED_FOREST = 180
    BASALT_DELTAS = 181
    JAGGED_PEAKS = 182
    FROZEN_PEAKS = 183
    SNOWY_SLOPES = 184
    GROVE = 185
    MEADOW = 186
    LUSH_CAVES = 187
    DRIPSTONE_CAVES = 188
    STONY_PEAKS = 189


"""
Biome region enums, a region determines what type variable blocks are replaced with,
i.e. a forest will have wooden variable blocks etc. """


class biome_regions(ExtendedEnum):
    FOREST = 1
    PLAINS = 2
    DESERT = 3
    COLD = 4
    SAVANNA = 5
